### ISSUE TITLE
1.17 ?

### ISSUE THREAD

**Issue by Chuunkyz** [mrsterner/phantomblood#3]
hey, haema 1.17 is pretty stable. so why not updating this one too ? :)

**Comment by mrsterner** [comment]
If i just wanted to update it would already be updated, but im adding a lot more stands and im doing that in my spare time, however, we are close to release of the 2.0 update for 1.17

**Comment by NixityNull** [comment]
> If i just wanted to update it would already be updated, but im adding a lot more stands and im doing that in my spare time, however, we are close to release of the 2.0 update for 1.17

Les GOOO
