### ISSUE TITLE
mod crashes game

### ISSUE THREAD

**Issue by Catmole132** [mrsterner/phantomblood#4]
[crash-2021-09-13_14.03.01-client.txt](https://github.com/mrsterner/phantomblood/files/7154092/crash-2021-09-13_14.03.01-client.txt)
Here's my crash report. It just crashes the game, which sucks because the mod looks cool. It works fine when i remove it.

**Comment by mrsterner** [comment]
You need Geckolib installed to use this mod

**Comment by Catmole132** [comment]
I did have it installed

**Comment by Catmole132** [comment]
If it didn't show up in the crashlog idk why but I made sure I had it in there. I checked like 50 times.

**Comment by mrsterner** [comment]
Caused by: java.lang.ClassNotFoundException: software.bernie.geckolib3.GeckoLib. Its not in the mod list in the crashlog and make sure you use the fabric version of the mod, there is a forge version of Geckolib

**Comment by Catmole132** [comment]
Oh my fucking god I'm an idiot. I downloaded the fucking forge version. Thank you and excuse my stupidity
